export const PG_FLYWAY_DRY_RUN = 'PG_FLYWAY_DRY_RUN';
export const PG_FLYWAY_DATABASE_URL = 'PG_FLYWAY_DATABASE_URL';
export const PG_FLYWAY_LOCATIONS = 'PG_FLYWAY_LOCATIONS';
export const PG_FLYWAY_HISTORY_TABLE = 'PG_FLYWAY_HISTORY_TABLE';
export const PG_FLYWAY_HISTORY_SCHEMA = 'PG_FLYWAY_HISTORY_SCHEMA';
export const PG_FLYWAY_SQL_MIGRATION_SUFFIXES = 'PG_FLYWAY_SQL_MIGRATION_SUFFIXES';
export const PG_FLYWAY_SQL_MIGRATION_SEPARATOR = 'PG_FLYWAY_SQL_MIGRATION_SEPARATOR';
export const PG_FLYWAY_SQL_MIGRATION_STATEMENT_SEPARATOR = 'PG_FLYWAY_SQL_MIGRATION_STATEMENT_SEPARATOR';
