export const PG_CREATE_DB_DRY_RUN = 'PG_CREATE_DB_DRY_RUN';
export const PG_CREATE_DB_ROOT_DATABASE_URL = 'PG_CREATE_DB_ROOT_DATABASE_URL';
export const PG_CREATE_DB_APP_DATABASE_URL = 'PG_CREATE_DB_APP_DATABASE_URL';
export const PG_CREATE_DB_FORCE_CHANGE_USERNAME = 'PG_CREATE_DB_FORCE_CHANGE_USERNAME';
export const PG_CREATE_DB_FORCE_CHANGE_PASSWORD = 'PG_CREATE_DB_FORCE_CHANGE_PASSWORD';
export const PG_CREATE_DB_DROP_APP_DATABASE = 'PG_CREATE_DB_DROP_APP_DATABASE';
export const PG_CREATE_DB_EXTENSIONS = 'PG_CREATE_DB_EXTENSIONS';
